export interface Review {
  id: string
  author: string
  rating: number
  text: string
  date: string
  source: 'Google' | 'BBB' | 'Other'
}

export const REVIEWS: Review[] = [
  {
    id: '1',
    author: 'Jackie Dellwo',
    rating: 5,
    text: 'Advanced Roofing & Siding has been amazing to work with. They were so responsive and helpful anytime I had a question. We had a lot of issues with our insurance company fighting the claim and they really went to bat for us to push the claim through.',
    date: '2 months ago',
    source: 'Google',
  },
  {
    id: '2',
    author: 'Abe Ambriz',
    rating: 5,
    text: 'It was excellent working with this contractor. They had open communication and answered all my questions about the claim process. They helped me when insurance was denying the damage — they fought until it was approved for the roof and siding replacement.',
    date: '9 months ago',
    source: 'Google',
  },
  {
    id: '3',
    author: 'Steve V',
    rating: 5,
    text: 'Our project with Advanced Roofing and Siding went very well. From the estimating and quote stage to the final install and cleanup. Stacy was there every step of the way to ensure that everything was completed on-time and on-budget. The new roof looks great! Very happy with our experience!',
    date: '1 year ago',
    source: 'Google',
  },
  {
    id: '4',
    author: 'Barbara Knotz',
    rating: 5,
    text: 'Advanced Roofing & Siding did an exceptional job installing our new roof! The salesman Eric was very thorough in his explanation of the proposed job with no pressure to sign a contract! The installers worked diligently in the horrible heat that day! I highly recommend Advanced Roofing & Siding if you\'re needing a roof!',
    date: '1 year ago',
    source: 'Google',
  },
  {
    id: '5',
    author: 'John Milbradt',
    rating: 5,
    text: 'Everything was done in a few hours. The guys made sure everything was cleaned up — especially using a magnet to make sure there were no nails on the ground. Advanced Roofing went above and beyond. We are very satisfied with everything they had done.',
    date: '2 years ago',
    source: 'Google',
  },
  {
    id: '6',
    author: 'Kenan McCracken',
    rating: 5,
    text: 'I worked with Travis to get my roof replaced. He was a pleasure to work with and guided me through the entire process. I live out of state and the team handled the entire project within 2 days. They even touched up a couple of pieces I personally asked for without hesitation. Thank you, Travis!',
    date: '1 year ago',
    source: 'Google',
  },
  {
    id: '7',
    author: 'Bailey Dailey',
    rating: 5,
    text: 'Travis Richter did a great job communicating with us in order to get our new roof completed! Very happy with Advanced Roofing. They did a great job cleaning up the yard after. Stacy even reached out to check in and see if we had any concerns (which we didn\'t). Highly recommend them!',
    date: '1 year ago',
    source: 'Google',
  },
  {
    id: '8',
    author: 'David Haas',
    rating: 5,
    text: 'The crew at Advanced Roofing and Siding worked in a professional manner to complete our roof replacement after hail damage. Their experience working with the insurance company was evident as they advocated for our best interests. Overall, the project came together well, even when faced with setbacks.',
    date: '2 years ago',
    source: 'Google',
  },
  {
    id: '9',
    author: 'Rich Harter',
    rating: 5,
    text: 'Reached out to Advanced on a Monday and by Friday they were on-site doing the roof on my house and detached garage. Can\'t thank Stacy and his team enough for all the hard work, especially on such short notice. Both roofs look amazing!',
    date: '2 years ago',
    source: 'Google',
  },
  {
    id: '10',
    author: 'Brad Solheid',
    rating: 5,
    text: 'Absolutely excellent. Quality work, honest pricing. Stacy is a very personable fella. I completely felt comfortable with him and his work. He truly cares about you and the work he performs. Best contractor I\'ve ever worked with.',
    date: '2 years ago',
    source: 'Google',
  },
  {
    id: '11',
    author: 'Julie Rosenberg',
    rating: 5,
    text: 'Advanced Roofing did my roof in 2016. They did a great job then so I had them side my home. It turned out amazing. The crew took care of all the details I wanted. They finished my house in 2 days. I\'m very happy!',
    date: '3 years ago',
    source: 'Google',
  },
  {
    id: '12',
    author: 'Wyatt Norby',
    rating: 5,
    text: 'An outstanding company. Very happy with the work they did on our home with the new roof. Travis and Stacy are very easy to work with and the roofing crew did an exceptional job. 10/10 recommended.',
    date: '1 year ago',
    source: 'Google',
  },
  {
    id: '13',
    author: 'Carolyn Raber',
    rating: 5,
    text: 'Travis at Advanced worked tirelessly with my insurance company to get my roof done! They finished it and did a great job — but to top it off they fixed a fascia that wasn\'t included in the insurance quote! Their customer service was outstanding!!',
    date: '1 year ago',
    source: 'Google',
  },
  {
    id: '14',
    author: 'Cori Johnson',
    rating: 5,
    text: 'Advanced Roofing and Siding is a fantastic company to work with. They are extremely professional and very knowledgeable and skilled in their field. Overall, they did an excellent job on our roof from start to finish.',
    date: '2 years ago',
    source: 'Google',
  },
  {
    id: '15',
    author: 'Cindi Hatlestad',
    rating: 5,
    text: 'Had a great experience working with Advanced Roofing & Siding from the time of the estimate through final project. They were very easy to communicate with, answered questions promptly, and work was completed efficiently and to our satisfaction.',
    date: '2 years ago',
    source: 'Google',
  },
  {
    id: '16',
    author: 'David Horns',
    rating: 5,
    text: 'The team showed up on time and completed the job very quickly and efficiently. All communication, before, during, and after job completion was excellent. We were pleased with the quality of the work and materials and would recommend them to anyone.',
    date: '3 years ago',
    source: 'Google',
  },
  {
    id: '17',
    author: 'Kevin Reilly',
    rating: 5,
    text: 'Advanced Roofing did a great job taking care of the storm damage on our house. Very professional and workmanship was awesome. Stacy checked with me many times to make sure everything was up to my standards. Will definitely use them again.',
    date: '3 years ago',
    source: 'Google',
  },
  {
    id: '18',
    author: 'Tomo Riley',
    rating: 5,
    text: 'Nick came to our house to patch a leak. He inspected the whole roof and patched the plumbing vents. He took time to explain what he found and described it. He was very thorough, polite, and friendly! I will be having Advanced Roofing put my new roof on this summer! Very satisfied and would recommend them!',
    date: '4 years ago',
    source: 'Google',
  },
  {
    id: '19',
    author: 'Scott Johnson',
    rating: 5,
    text: 'Advanced Roofing did an amazing job — done in one day. Easy to work with and very professional. Would highly recommend them.',
    date: '2 years ago',
    source: 'Google',
  },
  {
    id: '20',
    author: 'Kyle Johnson',
    rating: 5,
    text: 'By far the best experience I\'ve dealt with from start to finish. Stacy and Hope were excellent to work with and made it easy to do business with. If you want the job done right, go with Advanced Roofing and Siding!',
    date: '2 years ago',
    source: 'Google',
  },
  {
    id: '21',
    author: 'Janie Killian',
    rating: 5,
    text: 'We had a great experience with our reroof. Nice and quick. They kept the tear-off out of my flowers. Thank you!',
    date: '3 years ago',
    source: 'Google',
  },
  {
    id: '22',
    author: 'Ty Adams',
    rating: 5,
    text: 'I know that Advanced Roofing & Siding has their customers\' best interest at heart. Stacy Lehn, the owner, is very involved in his business and is always looking for ways to improve the business and the customer\'s experience.',
    date: '3 years ago',
    source: 'Google',
  },
  {
    id: '23',
    author: 'Brian Opp',
    rating: 5,
    text: 'Advanced Roofing is an amazing company. Easy to work with, they really look out for the homeowner. Highly recommend them!',
    date: '3 years ago',
    source: 'Google',
  },
  {
    id: '24',
    author: 'Kelly Schudi',
    rating: 5,
    text: 'Advanced Roofing did a nice job for us. They worked with our insurance company to make it happen. Stacy kept open communication with me, as that is important to me. I would highly recommend them as a roofing company.',
    date: '4 years ago',
    source: 'Google',
  },
  {
    id: '25',
    author: 'Vicki Heller',
    rating: 5,
    text: 'If anyone is looking for a dependable, honest company to work with, this would be Advanced Roofing and Siding. We just had our roof replaced by Advanced Roofing. The owner Stacy and his crew come highly recommended by both Craig and I.',
    date: '2 years ago',
    source: 'Google',
  },
  {
    id: '26',
    author: 'Jake K',
    rating: 5,
    text: 'Travis was great to work with and very knowledgeable about the materials installed on my project. Would highly recommend Advanced Roofing to anyone.',
    date: '2 years ago',
    source: 'Google',
  },
  {
    id: '27',
    author: 'Michelle Smallidge',
    rating: 5,
    text: 'Our association had Advanced Roofing & Siding do our roofs. The roofers were amazing — they showed up early, worked late, and made sure everything was cleaned up at the end of the day. They were very professional, hardworking, and fast.',
    date: '2 years ago',
    source: 'Google',
  },
  {
    id: '28',
    author: 'Katie Ciani',
    rating: 5,
    text: 'Advanced Roofing and Siding has been a pleasure to work with. They do quality work, always putting the client first. Stacy is responsive and very knowledgeable. I definitely recommend them.',
    date: '2 years ago',
    source: 'Google',
  },
  {
    id: '29',
    author: 'Macky Schmitt',
    rating: 5,
    text: 'Nothing less than 5 stars for Advanced Roofing! We had our roof shingled in 1 day! Yes, 1 day! From start to finish, Stacy was professional, took care of all the insurance needs, cleaned up as the crew went, and were extremely fast.',
    date: '3 years ago',
    source: 'Google',
  },
  {
    id: '30',
    author: 'Connor Flood',
    rating: 5,
    text: 'I was truly shocked at how quick their response time is. The owner, Stacy, picked up my call on the first ring and then pulled to the side of the road to pull up the address I needed a roof inspected on. He told me his project manager would be there the next morning — and he was.',
    date: '2 years ago',
    source: 'Google',
  },
  {
    id: '31',
    author: 'Andrew Benson',
    rating: 5,
    text: 'Stacy is the man! Not only his craftsmanship and attention to detail, but he is an honest, real person. You can tell when you talk to him he cares about making sure you are happy. Strongly suggest!',
    date: '3 years ago',
    source: 'Google',
  },
  {
    id: '32',
    author: 'Scott Ricks',
    rating: 5,
    text: 'Highly recommend Advanced!! They were very responsive and completed our project with ease. Huge thanks to all the team involved in getting it completed on time and on budget.',
    date: '2 years ago',
    source: 'Google',
  },
  {
    id: '33',
    author: 'Nancy Carpenter',
    rating: 5,
    text: 'Big shout out to Advanced Roofing Oak Grove! They were out and replaced our hail damaged roof in 1 day — from start of shingles off to new shingles on! Very professional and clean. We would highly recommend them to anyone in need!',
    date: '3 years ago',
    source: 'Google',
  },
  {
    id: '34',
    author: 'Roni Stockinger',
    rating: 5,
    text: 'I have worked with the team at Advanced Roofing on multiple occasions. They are always helpful and have great communication.',
    date: '2 years ago',
    source: 'Google',
  },
  {
    id: '35',
    author: 'GRAY 1',
    rating: 5,
    text: 'Advanced Roofing and Siding Inc. did a great job on getting my house and garage roof replaced after the hail storm we had in June. They were really easy to talk to and kept me updated on everything during the process. Nice job!',
    date: '2 years ago',
    source: 'Google',
  },
  {
    id: '36',
    author: 'Nicole Ricks',
    rating: 5,
    text: 'I have had the pleasure of working with Advanced Roofing and Siding for over 12 years. Great owner and great team to work with!',
    date: '1 year ago',
    source: 'Google',
  },
  {
    id: '37',
    author: 'Ben Theis',
    rating: 5,
    text: 'Stacy with Advanced Roofing is really passionate and knows his stuff when it comes to roofing. It was a pleasure working with him and his team and I would recommend them if you are looking for roofing repair or work.',
    date: '3 years ago',
    source: 'Google',
  },
  {
    id: '38',
    author: 'Andy Kusler',
    rating: 5,
    text: 'Easy to work with and any minor disagreements were handled quickly and fairly. Patient while dealing with insurance delays. Will definitely call again if the need arises.',
    date: '3 years ago',
    source: 'Google',
  },
  {
    id: '39',
    author: 'John Moroney',
    rating: 5,
    text: 'Excellent work, great price, and rapid response! Thanks for helping get our house ready for sale. Quality is high and I was really impressed by how hard your team works and how neat they were. I would highly recommend and hope to have you do our planned project in the future!',
    date: '4 years ago',
    source: 'Google',
  },
  {
    id: '40',
    author: 'Jess Brehmer',
    rating: 5,
    text: 'They came out within a couple hours of contacting them to take a look at an urgent matter, which was very much appreciated. Responsive and professional.',
    date: '3 years ago',
    source: 'Google',
  },
  {
    id: '41',
    author: 'Theresa Kirchner',
    rating: 5,
    text: 'Advanced Roofing did a great job on our parents\' home — the best quality at the best price. Workmanship was outstanding, their efficiency and quality was deeply appreciated.',
    date: '4 years ago',
    source: 'Google',
  },
  {
    id: '42',
    author: 'Mer Mer',
    rating: 5,
    text: 'No pushy sales, no pressure — only helpful information and facts. I got great value and top notch service! The entire process was smooth. Most importantly I was always informed of what and when to expect the next step. When questions came up, I got immediate responses.',
    date: '3 years ago',
    source: 'Google',
  },
  {
    id: '43',
    author: 'Jeff Kotula',
    rating: 5,
    text: 'Great job by the installation crew replacing the roof while protecting the garden plantings around the house! It was also a seamless integration with our insurance company. Easy as pie all around! Really went the extra mile to get all the details done too!',
    date: '3 years ago',
    source: 'Google',
  },
  {
    id: '44',
    author: 'James Krause',
    rating: 5,
    text: 'Advanced Roofing and Siding did a great job on replacing my roof from hail damage. Very professional and easy to work with.',
    date: '3 years ago',
    source: 'Google',
  },
  {
    id: '45',
    author: 'Ryan Whalen',
    rating: 5,
    text: 'The work done on our home was very high quality and attentive to detail. It was a pleasure working with both Travis and Stacy.',
    date: '4 years ago',
    source: 'Google',
  },
  {
    id: '46',
    author: 'Ken Daly',
    rating: 5,
    text: 'Great job on roof damaged by storm. Easy to work with and done in a timely manner! Would definitely use them again!',
    date: '3 years ago',
    source: 'Google',
  },
  {
    id: '47',
    author: 'Dave Wills',
    rating: 5,
    text: 'Top-notch company, helps with the entire process including working with the insurance companies. We\'ve used them for ourselves and clients for years.',
    date: '4 years ago',
    source: 'Google',
  },
  {
    id: '48',
    author: 'Teresa Orpen',
    rating: 5,
    text: 'Appreciate the professionalism of everyone we talked and worked with. We had a detached garage roof redone, and even though it was a small job, I feel like we were given the same attention that one would get if we had a huge project. Would work with again.',
    date: '3 years ago',
    source: 'Google',
  },
  {
    id: '49',
    author: 'Sandy Golembeck',
    rating: 5,
    text: 'Excellent service. Roof well done and on time as promised. Staff worked efficiently and when done cleaned up without a nail or any debris left behind. Thank you.',
    date: '3 years ago',
    source: 'Google',
  },
  {
    id: '50',
    author: 'Chris Kline',
    rating: 5,
    text: 'Advanced Roofing & Siding did an amazing job on our roof. Very professional service. Would highly recommend.',
    date: '4 years ago',
    source: 'Google',
  },
  {
    id: '51',
    author: 'Allen Mostue',
    rating: 5,
    text: 'They did an amazing job on our roof and worked with our insurance company. Absolutely was the right company for the job.',
    date: '4 years ago',
    source: 'Google',
  },
  {
    id: '52',
    author: 'Craig Davis',
    rating: 5,
    text: 'Everything was done perfect and on time. Very organized and professional business. I would highly recommend the company.',
    date: '3 years ago',
    source: 'Google',
  },
  {
    id: '53',
    author: 'David Fischer',
    rating: 5,
    text: 'From the friendly knock at the door to the dumpsters being picked up, I couldn\'t be happier with the job from Advanced Roofing.',
    date: '4 years ago',
    source: 'Google',
  },
  {
    id: '54',
    author: 'Kim',
    rating: 5,
    text: 'Great to work with and very persistent in ensuring the property owner was treated fairly by their insurance company and received all the benefits they were eligible for. I would definitely use them again for future projects.',
    date: '2 years ago',
    source: 'Google',
  },
  {
    id: '55',
    author: 'Shelly Schermerhorn',
    rating: 5,
    text: 'We highly recommend working with Advanced Roofing & Siding. From start to finish, the team is professional, responsive, and easy to work with. They communicate clearly throughout the entire process and make everything feel stress-free. This is an honest and reliable roofing company!',
    date: '1 year ago',
    source: 'Google',
  },
  {
    id: '56',
    author: 'Paula Ervin',
    rating: 5,
    text: 'I called to ask advice on roofing. The gentleman I spoke with was very willing to share his knowledge with me. I will most definitely give Advanced Roofing and Siding\'s number out to anyone who asks.',
    date: '2 years ago',
    source: 'Google',
  },
  {
    id: '57',
    author: 'Jordan Gardas',
    rating: 5,
    text: 'Recently had our roof replaced due to storm damage. Advanced was very easy to deal with and did a very professional job. Would recommend them to everyone!',
    date: '3 years ago',
    source: 'Google',
  },
  {
    id: '58',
    author: 'Tommy Fitz',
    rating: 5,
    text: 'I\'ve sent multiple referrals to Stacy with Advanced and will continue to do so. Top tier work. Thank you!',
    date: '3 years ago',
    source: 'Google',
  },
  {
    id: '59',
    author: 'Brent Halstensen',
    rating: 5,
    text: 'Great company to work with. Within budget and done in a professional and timely manner. Thanks Stacy!',
    date: '4 years ago',
    source: 'Google',
  },
  {
    id: '60',
    author: 'Rich Holen',
    rating: 5,
    text: 'Great company to work with. They have roofed all of our properties. Would highly recommend them.',
    date: '4 years ago',
    source: 'Google',
  },
]

export const AVERAGE_RATING = 4.9
export const TOTAL_REVIEWS = 160

// Featured reviews for homepage — pick 3 that are substantive and varied
export const FEATURED_REVIEWS = [REVIEWS[2], REVIEWS[9], REVIEWS[12]]
